all:
	clang -fobjc-arc screen_capture.m -o screen_capture \
  -framework Foundation \
  -framework CoreGraphics \
  -framework ScreenCaptureKit \
  -framework CoreVideo \
  -framework ImageIO \
  -framework UniformTypeIdentifiers
